### ISSUE TITLE
03 - Eu, como desenvolvedor, desejo refatorar o código para garantir manutenibilidade.

### ISSUE THREAD

**Issue by renatasoares** [fga-gpp-mds/2016.2-MissaoNascente#7]
#### _**Tasks**_

- [ ] Aplicar boas práticas de _Android_.

- [ ] Refatorar _models_ para atingir melhores indicadores nas métricas.

- [x] Refatorar _controllers_ para atingir melhores indicadores nas métricas.
